<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrentDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        DB::table('gurus')->truncate();
        DB::table('pastis')->truncate();
        DB::table('kawasans')->truncate();
        DB::table('model_has_roles')->truncate();
        DB::table('users')->truncate();
        DB::table('roles')->truncate();
        DB::table('program_title_options')->truncate();
        DB::table('program_statuses')->truncate();
        DB::table('pemarkahan_title_options')->truncate();
        DB::table('financial_transaction_types')->truncate();
        DB::table('ajk_positions')->truncate();

        DB::table('program_title_options')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'title' => 'Sukan PASTI',
            'markah' => 1,
            'sort_order' => 1,
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
          1 => 
          array (
            'id' => 2,
            'title' => 'Usrah',
            'markah' => 1,
            'sort_order' => 2,
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
          2 => 
          array (
            'id' => 3,
            'title' => 'Hari Anugerah Prestasi PASTI',
            'markah' => 1,
            'sort_order' => 3,
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
        )
        );

        DB::table('program_statuses')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'Hadir',
            'code' => 'HADIR',
            'is_hadir' => 1,
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'Tidak Hadir',
            'code' => 'TIDAK_HADIR',
            'is_hadir' => 0,
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
        )
        );

        DB::table('pemarkahan_title_options')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'title' => 'Penaziran Infrastruktur',
            'sort_order' => 1,
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
          1 => 
          array (
            'id' => 2,
            'title' => 'Penaziran Pengajaran Guru',
            'sort_order' => 2,
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
        )
        );

        DB::table('financial_transaction_types')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'Lain-lain',
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:38',
            'updated_at' => '2026-04-03 16:46:38',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'Claim',
            'is_active' => 1,
            'created_by' => NULL,
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
        )
        );

        DB::table('ajk_positions')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'Pengarah Program',
            'description' => 'Bertanggungjawab menyelaras keseluruhan perancangan dan pelaksanaan program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'Setiausaha',
            'description' => 'Mengurus surat-menyurat, dokumentasi dan laporan program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          2 => 
          array (
            'id' => 3,
            'name' => 'Bendahari',
            'description' => 'Mengurus kewangan termasuk bajet, kutipan dan perbelanjaan.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          3 => 
          array (
            'id' => 4,
            'name' => 'AJK Protokol',
            'description' => 'Mengurus susunan kehadiran tetamu dan memastikan perjalanan majlis mengikut etika.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          4 => 
          array (
            'id' => 5,
            'name' => 'AJK Aturcara Majlis',
            'description' => 'Menyusun dan memantau perjalanan aturcara program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          5 => 
          array (
            'id' => 6,
            'name' => 'Pengacara Majlis',
            'description' => 'Mengendalikan majlis dan memastikan program berjalan lancar mengikut aturcara.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          6 => 
          array (
            'id' => 7,
            'name' => 'AJK Pendaftaran',
            'description' => 'Mengurus kehadiran peserta dan rekod pendaftaran.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          7 => 
          array (
            'id' => 8,
            'name' => 'AJK Jamuan',
            'description' => 'Menyediakan dan mengurus makanan serta minuman.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          8 => 
          array (
            'id' => 9,
            'name' => 'AJK Kebersihan',
            'description' => 'Memastikan kebersihan kawasan sebelum, semasa dan selepas program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          9 => 
          array (
            'id' => 10,
            'name' => 'AJK Logistik',
            'description' => 'Mengurus penyediaan, susun atur dan peralatan program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          10 => 
          array (
            'id' => 11,
            'name' => 'AJK Dokumentasi',
            'description' => 'Mengambil gambar, video dan menyediakan rekod program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          11 => 
          array (
            'id' => 12,
            'name' => 'AJK Publisiti',
            'description' => 'Menghebahkan program melalui pelbagai saluran.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          12 => 
          array (
            'id' => 13,
            'name' => 'AJK Kawalan Murid',
            'description' => 'Mengawal disiplin dan pergerakan murid sepanjang program.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          13 => 
          array (
            'id' => 14,
            'name' => 'AJK Hadiah & Sijil',
            'description' => 'Menyediakan dan mengurus penyampaian hadiah serta sijil.',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
        )
        );

        DB::table('gurus')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'user_id' => 2,
            'pasti_id' => NULL,
            'name' => 'Fatimah binti mohamad',
            'email' => 'fatimah3015@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:02',
            'updated_at' => '2026-04-03 18:09:02',
          ),
          1 => 
          array (
            'id' => 2,
            'user_id' => 3,
            'pasti_id' => NULL,
            'name' => 'Nur Fatin Izaty Binti Mohd Khair Johari',
            'email' => 'joharifatin59@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          2 => 
          array (
            'id' => 3,
            'user_id' => 4,
            'pasti_id' => NULL,
            'name' => 'Nor Fatin Binti Mohd Yusoff',
            'email' => 'fatinyusoff0@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          3 => 
          array (
            'id' => 4,
            'user_id' => 5,
            'pasti_id' => NULL,
            'name' => 'Noraini binti Abd Rahman',
            'email' => 'norainiabdrahman83@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          4 => 
          array (
            'id' => 5,
            'user_id' => 6,
            'pasti_id' => NULL,
            'name' => 'Rosmimi Bt Rusdi',
            'email' => 'rosmimirusdi28@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          5 => 
          array (
            'id' => 6,
            'user_id' => 7,
            'pasti_id' => NULL,
            'name' => 'Mahirah bt dzakaria',
            'email' => 'mahirahdzakaria@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          6 => 
          array (
            'id' => 7,
            'user_id' => 8,
            'pasti_id' => NULL,
            'name' => 'Asma Hani Binti Abdul Rani',
            'email' => 'aasmahaniabdulrani@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          7 => 
          array (
            'id' => 8,
            'user_id' => 9,
            'pasti_id' => NULL,
            'name' => 'Noor Ummi binti Umar',
            'email' => 'noorummiumar@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          8 => 
          array (
            'id' => 9,
            'user_id' => 10,
            'pasti_id' => NULL,
            'name' => 'Siti Munira binti Bidin',
            'email' => 's.munira6048@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          9 => 
          array (
            'id' => 10,
            'user_id' => 11,
            'pasti_id' => NULL,
            'name' => 'Noor Nadia Bt Mohamed',
            'email' => 'nadia85mohamed@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          10 => 
          array (
            'id' => 11,
            'user_id' => 12,
            'pasti_id' => NULL,
            'name' => 'Nor Atikah Binti Ibrahim',
            'email' => 'noratikahibrahim96@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          11 => 
          array (
            'id' => 12,
            'user_id' => 13,
            'pasti_id' => NULL,
            'name' => 'Rosnani Binti Zali',
            'email' => 'rosnanizali25@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          12 => 
          array (
            'id' => 13,
            'user_id' => 14,
            'pasti_id' => NULL,
            'name' => 'Halimahton saadiah bt hussain',
            'email' => 'imahsyifaimahsyifa@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          13 => 
          array (
            'id' => 14,
            'user_id' => 15,
            'pasti_id' => NULL,
            'name' => 'Siti Khadijah Binti Afifi',
            'email' => 'sitiafifi96@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          14 => 
          array (
            'id' => 15,
            'user_id' => 16,
            'pasti_id' => NULL,
            'name' => 'Adilah bt Abd Samad',
            'email' => 'adilahsumayyah@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          15 => 
          array (
            'id' => 16,
            'user_id' => 17,
            'pasti_id' => NULL,
            'name' => 'Nurul Ain Binti Abdul Samat',
            'email' => 'nurulain23.10.89@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          16 => 
          array (
            'id' => 17,
            'user_id' => 18,
            'pasti_id' => NULL,
            'name' => 'Suriani Binti Noordin',
            'email' => 'surianiinoordin@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          17 => 
          array (
            'id' => 18,
            'user_id' => 19,
            'pasti_id' => NULL,
            'name' => 'Fauziah Binti Shuhaimi',
            'email' => 'fauziahshuhaimi03@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          18 => 
          array (
            'id' => 19,
            'user_id' => 20,
            'pasti_id' => NULL,
            'name' => 'Roshaliza Bt Awang',
            'email' => 'roshalizaawang@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          19 => 
          array (
            'id' => 20,
            'user_id' => 21,
            'pasti_id' => NULL,
            'name' => 'Nazurah Bt Ismail',
            'email' => 'nzura3337@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          20 => 
          array (
            'id' => 21,
            'user_id' => 22,
            'pasti_id' => NULL,
            'name' => 'Noor Hafizah BT Baharom',
            'email' => 'fizah68@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          21 => 
          array (
            'id' => 22,
            'user_id' => 23,
            'pasti_id' => NULL,
            'name' => 'SITI RASHIDAH BINTI MD IDRUS',
            'email' => 'firash2704@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          22 => 
          array (
            'id' => 23,
            'user_id' => 24,
            'pasti_id' => NULL,
            'name' => 'Siti Zainab binti Ghazali',
            'email' => 'zainabghazali23@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          23 => 
          array (
            'id' => 24,
            'user_id' => 25,
            'pasti_id' => NULL,
            'name' => 'Mariani Binti Ab Rashid',
            'email' => 'rosmariayanie@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          24 => 
          array (
            'id' => 25,
            'user_id' => 26,
            'pasti_id' => NULL,
            'name' => 'Nuradilah Farhanabinti Harum',
            'email' => 'farhanaharun009@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          25 => 
          array (
            'id' => 26,
            'user_id' => 27,
            'pasti_id' => NULL,
            'name' => 'Nooraini bint tvi Haya',
            'email' => 'ainihaya71@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          26 => 
          array (
            'id' => 27,
            'user_id' => 28,
            'pasti_id' => NULL,
            'name' => 'Jareah bt ahmad',
            'email' => 'jariahahmad89@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          27 => 
          array (
            'id' => 28,
            'user_id' => 29,
            'pasti_id' => NULL,
            'name' => 'A\'fifah bt mohamed',
            'email' => 'afifahjasmee@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          28 => 
          array (
            'id' => 29,
            'user_id' => 30,
            'pasti_id' => NULL,
            'name' => 'Siti Najwa Binti Sulaiman',
            'email' => 'snnajwa15@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          29 => 
          array (
            'id' => 30,
            'user_id' => 31,
            'pasti_id' => NULL,
            'name' => 'Nor Khuzamah binti Ahmad',
            'email' => 'khuzaimah581@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          30 => 
          array (
            'id' => 31,
            'user_id' => 32,
            'pasti_id' => NULL,
            'name' => 'SITI NOOR BT ZAKARIA.',
            'email' => 'sitinoorzakaria36@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          31 => 
          array (
            'id' => 32,
            'user_id' => 33,
            'pasti_id' => NULL,
            'name' => 'Mashitah Binti Ayub',
            'email' => 'mashitahmasyie950820@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          32 => 
          array (
            'id' => 33,
            'user_id' => 34,
            'pasti_id' => NULL,
            'name' => 'Sarina Binti Ahmad',
            'email' => 'sarinaahmad508@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          33 => 
          array (
            'id' => 34,
            'user_id' => 35,
            'pasti_id' => NULL,
            'name' => 'Fatin Zubaidah binti Ghazali',
            'email' => 'fatin96ghazali@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          34 => 
          array (
            'id' => 35,
            'user_id' => 36,
            'pasti_id' => NULL,
            'name' => 'Nafizah binti Dollah',
            'email' => 'nafizahdollah61@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          35 => 
          array (
            'id' => 36,
            'user_id' => 37,
            'pasti_id' => NULL,
            'name' => 'Roslina Lahman',
            'email' => 'linalahman78@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:11',
            'updated_at' => '2026-04-03 18:09:11',
          ),
          36 => 
          array (
            'id' => 37,
            'user_id' => 38,
            'pasti_id' => NULL,
            'name' => 'Nur Famiza Fazilah',
            'email' => 'nazamiza8389@gmail.com',
            'avatar_path' => NULL,
            'is_assistant' => 0,
            'phone' => NULL,
            'marital_status' => NULL,
            'kursus_guru' => NULL,
            'joined_at' => NULL,
            'active' => 1,
            'terima_anugerah' => 0,
            'created_at' => '2026-04-03 18:09:11',
            'updated_at' => '2026-04-03 18:09:11',
          ),
        )
        );

        DB::table('pastis')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'kawasan_id' => 2,
            'name' => 'AL-ABROR',
            'code' => 'K100111',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:48:02',
            'updated_at' => '2026-04-03 16:48:12',
          ),
          1 => 
          array (
            'id' => 2,
            'kawasan_id' => 1,
            'name' => 'AL-AZFAR',
            'code' => 'K100202',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:48:34',
            'updated_at' => '2026-04-03 16:48:34',
          ),
          2 => 
          array (
            'id' => 3,
            'kawasan_id' => 2,
            'name' => 'AL-BADRU',
            'code' => 'K100102',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:48:51',
            'updated_at' => '2026-04-03 16:49:03',
          ),
          3 => 
          array (
            'id' => 4,
            'kawasan_id' => 2,
            'name' => 'AL-EHSAN',
            'code' => 'K100103',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:49:23',
            'updated_at' => '2026-04-03 16:49:23',
          ),
          4 => 
          array (
            'id' => 5,
            'kawasan_id' => 2,
            'name' => 'AL-FALAH',
            'code' => 'K100104',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:49:46',
            'updated_at' => '2026-04-03 16:49:46',
          ),
          5 => 
          array (
            'id' => 6,
            'kawasan_id' => 1,
            'name' => 'AL-FAWWAZ',
            'code' => 'K100203',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:50:03',
            'updated_at' => '2026-04-03 16:50:03',
          ),
          6 => 
          array (
            'id' => 7,
            'kawasan_id' => 2,
            'name' => 'AL-FURQAN',
            'code' => 'K100105',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:50:27',
            'updated_at' => '2026-04-03 16:50:27',
          ),
          7 => 
          array (
            'id' => 8,
            'kawasan_id' => 1,
            'name' => 'AL-HUSNA',
            'code' => 'K100204',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:50:49',
            'updated_at' => '2026-04-03 16:50:49',
          ),
          8 => 
          array (
            'id' => 9,
            'kawasan_id' => 1,
            'name' => 'AL-MISBAH',
            'code' => 'K100205',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:51:06',
            'updated_at' => '2026-04-03 16:51:06',
          ),
          9 => 
          array (
            'id' => 10,
            'kawasan_id' => 2,
            'name' => 'AN-NAJAAH',
            'code' => 'K100107',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:51:26',
            'updated_at' => '2026-04-03 16:51:26',
          ),
          10 => 
          array (
            'id' => 11,
            'kawasan_id' => 2,
            'name' => 'AN-NASYEIN',
            'code' => 'K100108',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:51:43',
            'updated_at' => '2026-04-03 16:51:43',
          ),
          11 => 
          array (
            'id' => 12,
            'kawasan_id' => 1,
            'name' => 'BADRUL HUDA',
            'code' => 'K100211',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:52:02',
            'updated_at' => '2026-04-03 16:52:02',
          ),
          12 => 
          array (
            'id' => 13,
            'kawasan_id' => 1,
            'name' => 'IBNU ABBAS',
            'code' => 'K100207',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:52:34',
            'updated_at' => '2026-04-03 16:52:34',
          ),
          13 => 
          array (
            'id' => 14,
            'kawasan_id' => 1,
            'name' => 'RAUDHATUL JANNAH',
            'code' => 'K100209',
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 16:52:51',
            'updated_at' => '2026-04-03 16:52:51',
          ),
          14 => 
          array (
            'id' => 15,
            'kawasan_id' => 1,
            'name' => 'AL-MUNA',
            'code' => NULL,
            'address' => NULL,
            'phone' => NULL,
            'manager_name' => NULL,
            'manager_phone' => NULL,
            'image_path' => NULL,
            'created_at' => '2026-04-03 18:09:33',
            'updated_at' => '2026-04-03 18:09:33',
          ),
        )
        );

        DB::table('kawasans')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'JENERI',
            'dun' => 'JENERI',
            'code' => NULL,
            'created_at' => '2026-04-03 16:48:02',
            'updated_at' => '2026-04-03 16:48:02',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'BELANTEK',
            'dun' => 'BELANTEK',
            'code' => NULL,
            'created_at' => '2026-04-03 16:48:12',
            'updated_at' => '2026-04-03 16:48:12',
          ),
        )
        );

        DB::table('model_has_roles')->insert(
        array (
          0 => 
          array (
            'role_id' => 1,
            'model_type' => 'App\\Models\\User',
            'model_id' => 1,
          ),
          1 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 2,
          ),
          2 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 3,
          ),
          3 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 4,
          ),
          4 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 5,
          ),
          5 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 6,
          ),
          6 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 7,
          ),
          7 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 8,
          ),
          8 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 9,
          ),
          9 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 10,
          ),
          10 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 11,
          ),
          11 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 12,
          ),
          12 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 13,
          ),
          13 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 14,
          ),
          14 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 15,
          ),
          15 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 16,
          ),
          16 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 17,
          ),
          17 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 18,
          ),
          18 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 19,
          ),
          19 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 20,
          ),
          20 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 21,
          ),
          21 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 22,
          ),
          22 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 23,
          ),
          23 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 24,
          ),
          24 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 25,
          ),
          25 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 26,
          ),
          26 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 27,
          ),
          27 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 28,
          ),
          28 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 29,
          ),
          29 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 30,
          ),
          30 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 31,
          ),
          31 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 32,
          ),
          32 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 33,
          ),
          33 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 34,
          ),
          34 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 35,
          ),
          35 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 36,
          ),
          36 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 37,
          ),
          37 => 
          array (
            'role_id' => 3,
            'model_type' => 'App\\Models\\User',
            'model_id' => 38,
          ),
        )
        );

        DB::table('users')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'Master Admin',
            'nama_samaran' => 'Master Admin',
            'tarikh_lahir' => '1985-12-03',
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'master@pasti',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => 'avatars/9ulV58rog3F5IggNAD86znFZhPz2AC7WFXlHh6xu.png',
            'email_verified_at' => '2026-04-03 16:46:39',
            'password' => '$2y$12$85nUC8bqIMB.cUcjWzJLBu.8FcjELmjg4JjsyEaK8ofueZ/.USrpm',
            'force_password_change' => 0,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:47:20',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'Fatimah binti mohamad',
            'nama_samaran' => 'Fatimah binti mohamad',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'fatimah3015@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:02',
            'password' => '$2y$12$8jsnUwhB9aAkB029J86KgO7gPvVPzZKiEEuaGeiIkJRtWUmN8y1gK',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:02',
            'updated_at' => '2026-04-03 18:09:02',
          ),
          2 => 
          array (
            'id' => 3,
            'name' => 'Nur Fatin Izaty Binti Mohd Khair Johari',
            'nama_samaran' => 'Nur Fatin Izaty Binti Mohd Khair Johari',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'joharifatin59@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:03',
            'password' => '$2y$12$ZFhr7qqgTOWR4/WgRD0qJuUuM1GCs8HWvETjEREK5eQZjKh8IzATS',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          3 => 
          array (
            'id' => 4,
            'name' => 'Nor Fatin Binti Mohd Yusoff',
            'nama_samaran' => 'Nor Fatin Binti Mohd Yusoff',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'fatinyusoff0@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:03',
            'password' => '$2y$12$RbISnP2yhgY9VN.Z.uQwVOErQLmdZv7./yfBXRItKBfnOfiA5yrXa',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          4 => 
          array (
            'id' => 5,
            'name' => 'Noraini binti Abd Rahman',
            'nama_samaran' => 'Noraini binti Abd Rahman',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'norainiabdrahman83@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:03',
            'password' => '$2y$12$Pu7InEOoM/3BydjS46wMUOPCrVLief7MRUz7s2sDtauBNf0EmLNRK',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          5 => 
          array (
            'id' => 6,
            'name' => 'Rosmimi Bt Rusdi',
            'nama_samaran' => 'Rosmimi Bt Rusdi',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'rosmimirusdi28@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:03',
            'password' => '$2y$12$tME9BYLYJOSn8fw.mVjmoOr997EX0Jnj.A19ZYgKSv7HrrOAzte1.',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:03',
            'updated_at' => '2026-04-03 18:09:03',
          ),
          6 => 
          array (
            'id' => 7,
            'name' => 'Mahirah bt dzakaria',
            'nama_samaran' => 'Mahirah bt dzakaria',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'mahirahdzakaria@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:04',
            'password' => '$2y$12$OHgTdYpMS.CUZa.8IgTx0uC8Osy7FNGXnN70ujQ9RCqlES2sBaRLi',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          7 => 
          array (
            'id' => 8,
            'name' => 'Asma Hani Binti Abdul Rani',
            'nama_samaran' => 'Asma Hani Binti Abdul Rani',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'aasmahaniabdulrani@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:04',
            'password' => '$2y$12$/zC9uUBAOuZW3kJaYTRwkORgrGXxJse1mlX5E6En5u.Ap47yAXdFO',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          8 => 
          array (
            'id' => 9,
            'name' => 'Noor Ummi binti Umar',
            'nama_samaran' => 'Noor Ummi binti Umar',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'noorummiumar@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:04',
            'password' => '$2y$12$PTgrkBxFuRalgtmCs6xU2eReLBu7Cm1b4IBaH00CVBT/8YP8IKZTK',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          9 => 
          array (
            'id' => 10,
            'name' => 'Siti Munira binti Bidin',
            'nama_samaran' => 'Siti Munira binti Bidin',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 's.munira6048@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:04',
            'password' => '$2y$12$4qbYLClKpIh/8CkyTcaK0.hc0FDd5RBtlE/8v0lTxrnGGoL.e33fq',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          10 => 
          array (
            'id' => 11,
            'name' => 'Noor Nadia Bt Mohamed',
            'nama_samaran' => 'Noor Nadia Bt Mohamed',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'nadia85mohamed@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:04',
            'password' => '$2y$12$.6B8sWykyYDmoLJgi4hZFu0ZgYkcM1QuCA8qBz6tJUcyXG/WQsux2',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:04',
            'updated_at' => '2026-04-03 18:09:04',
          ),
          11 => 
          array (
            'id' => 12,
            'name' => 'Nor Atikah Binti Ibrahim',
            'nama_samaran' => 'Nor Atikah Binti Ibrahim',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'noratikahibrahim96@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:05',
            'password' => '$2y$12$S5DRdwL/hDlV5jsQkHWgb.g0aDYIk/hhK1Q.Hqcv28..vwJbQQeXy',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          12 => 
          array (
            'id' => 13,
            'name' => 'Rosnani Binti Zali',
            'nama_samaran' => 'Rosnani Binti Zali',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'rosnanizali25@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:05',
            'password' => '$2y$12$ZxlsWh3geAxEmBk/oa49EOMhzVRoUuu5rLRmX45vw/qxByFj31wYm',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          13 => 
          array (
            'id' => 14,
            'name' => 'Halimahton saadiah bt hussain',
            'nama_samaran' => 'Halimahton saadiah bt hussain',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'imahsyifaimahsyifa@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:05',
            'password' => '$2y$12$Iwqj9QRd0qvTN0sOd3np9.nCyjLpkby4mLRUTjgrQNytqxEOa2b4W',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          14 => 
          array (
            'id' => 15,
            'name' => 'Siti Khadijah Binti Afifi',
            'nama_samaran' => 'Siti Khadijah Binti Afifi',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'sitiafifi96@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:05',
            'password' => '$2y$12$zINrhJofaqxYkdHTHQvCS.vqIJrzvaiAiGLB0qGKkPM3H30.U3eLK',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:05',
            'updated_at' => '2026-04-03 18:09:05',
          ),
          15 => 
          array (
            'id' => 16,
            'name' => 'Adilah bt Abd Samad',
            'nama_samaran' => 'Adilah bt Abd Samad',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'adilahsumayyah@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:06',
            'password' => '$2y$12$Cz1yOuJE6m0vM6BrbdXsUuRa3RfAb46P08mXqXvxGH.PQN.aP.cc6',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          16 => 
          array (
            'id' => 17,
            'name' => 'Nurul Ain Binti Abdul Samat',
            'nama_samaran' => 'Nurul Ain Binti Abdul Samat',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'nurulain23.10.89@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:06',
            'password' => '$2y$12$9.rdR1mappMaZ65AkDZ9oOopgk1P96kKbnYp3TS5gCJprhRu0kR7K',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          17 => 
          array (
            'id' => 18,
            'name' => 'Suriani Binti Noordin',
            'nama_samaran' => 'Suriani Binti Noordin',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'surianiinoordin@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:06',
            'password' => '$2y$12$Hs1IAG8IsdAXnAo4/nX7U.cpSUTwA4dvD1ix5/624B1ljsaB/iKW.',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          18 => 
          array (
            'id' => 19,
            'name' => 'Fauziah Binti Shuhaimi',
            'nama_samaran' => 'Fauziah Binti Shuhaimi',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'fauziahshuhaimi03@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:06',
            'password' => '$2y$12$w8gilzwtg0fZTVWaJplQd.Iq2T4dtA09xNS5naKG3hVx71uNu0s0m',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          19 => 
          array (
            'id' => 20,
            'name' => 'Roshaliza Bt Awang',
            'nama_samaran' => 'Roshaliza Bt Awang',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'roshalizaawang@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:06',
            'password' => '$2y$12$0ES9Q1xmm3YYXMLmHDL5mu/f29Cb8cTCD9rUf2MuKG7d78k3ugigy',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:06',
            'updated_at' => '2026-04-03 18:09:06',
          ),
          20 => 
          array (
            'id' => 21,
            'name' => 'Nazurah Bt Ismail',
            'nama_samaran' => 'Nazurah Bt Ismail',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'nzura3337@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:07',
            'password' => '$2y$12$GS/7c3sac8nfRCV..O0SkOyIG7uMXP97IMQhZIbxxTWD/KkaRfhyC',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          21 => 
          array (
            'id' => 22,
            'name' => 'Noor Hafizah BT Baharom',
            'nama_samaran' => 'Noor Hafizah BT Baharom',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'fizah68@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:07',
            'password' => '$2y$12$SgiIDhwC1ieZNMJH1vckXOqyZDbSSvmwl8whrV26vGV0wsgHaMNce',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          22 => 
          array (
            'id' => 23,
            'name' => 'SITI RASHIDAH BINTI MD IDRUS',
            'nama_samaran' => 'SITI RASHIDAH BINTI MD IDRUS',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'firash2704@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:07',
            'password' => '$2y$12$CmO1YbQ1K1UQLfBtBMOtoO6avSESQBp00I3Na0HMAzvNCdo3wbUcC',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          23 => 
          array (
            'id' => 24,
            'name' => 'Siti Zainab binti Ghazali',
            'nama_samaran' => 'Siti Zainab binti Ghazali',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'zainabghazali23@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:07',
            'password' => '$2y$12$XaljEFTPNUDxfIUGjdG5s.WHGBHIovhH42x.c99WsRhxrCuloW2s6',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:07',
            'updated_at' => '2026-04-03 18:09:07',
          ),
          24 => 
          array (
            'id' => 25,
            'name' => 'Mariani Binti Ab Rashid',
            'nama_samaran' => 'Mariani Binti Ab Rashid',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'rosmariayanie@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:08',
            'password' => '$2y$12$UhxyvrY4XjpqRqM9MmmD4uTeUu4XGh3ZuZPFfw9sNHDqEVcb6MJOi',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          25 => 
          array (
            'id' => 26,
            'name' => 'Nuradilah Farhanabinti Harum',
            'nama_samaran' => 'Nuradilah Farhanabinti Harum',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'farhanaharun009@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:08',
            'password' => '$2y$12$CTq65AzyVi/m2MWrI8bQpOFn6OTB1G5Q583IODtHRokqZ3xhTI76C',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          26 => 
          array (
            'id' => 27,
            'name' => 'Nooraini bint tvi Haya',
            'nama_samaran' => 'Nooraini bint tvi Haya',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'ainihaya71@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:08',
            'password' => '$2y$12$gPMTgo7mGd9w2/0xEfTSZe7XL06CYsgxhQjDHnzbH07dNayQSuRCK',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          27 => 
          array (
            'id' => 28,
            'name' => 'Jareah bt ahmad',
            'nama_samaran' => 'Jareah bt ahmad',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'jariahahmad89@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:08',
            'password' => '$2y$12$qixI34XyeZzqr8YVL4PKoON3OUgrAdeI.kuF5kTIf/ClP9I2XaDO.',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:08',
            'updated_at' => '2026-04-03 18:09:08',
          ),
          28 => 
          array (
            'id' => 29,
            'name' => 'A\'fifah bt mohamed',
            'nama_samaran' => 'A\'fifah bt mohamed',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'afifahjasmee@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:09',
            'password' => '$2y$12$WfH24SvXUTcgTYgFrVNTl.nhXTw8d8rmBOGvvuMXWb1YWn8PnbX9G',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          29 => 
          array (
            'id' => 30,
            'name' => 'Siti Najwa Binti Sulaiman',
            'nama_samaran' => 'Siti Najwa Binti Sulaiman',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'snnajwa15@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:09',
            'password' => '$2y$12$ikRX3UI/qaY6HvwJSoDPf.tjlxo7gwNKqxSrVZxuIA678ltgGRZg.',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          30 => 
          array (
            'id' => 31,
            'name' => 'Nor Khuzamah binti Ahmad',
            'nama_samaran' => 'Nor Khuzamah binti Ahmad',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'khuzaimah581@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:09',
            'password' => '$2y$12$nLSRB19SITt6S8DNOYVYDuEd0OIZfTJQy5vPvFwXZKqX4bRW8EG8m',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          31 => 
          array (
            'id' => 32,
            'name' => 'SITI NOOR BT ZAKARIA.',
            'nama_samaran' => 'SITI NOOR BT ZAKARIA.',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'sitinoorzakaria36@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:09',
            'password' => '$2y$12$.gzptPgCGiqbWtYUMAsbTetfR8nnjQq9rmkBciTQxxVQpw/ycxPrO',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          32 => 
          array (
            'id' => 33,
            'name' => 'Mashitah Binti Ayub',
            'nama_samaran' => 'Mashitah Binti Ayub',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'mashitahmasyie950820@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:09',
            'password' => '$2y$12$B0158CODc64SMF/Jsued5uMjQPtaMSobg.1LpeW1ZGoSw39d.uI2i',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:09',
            'updated_at' => '2026-04-03 18:09:09',
          ),
          33 => 
          array (
            'id' => 34,
            'name' => 'Sarina Binti Ahmad',
            'nama_samaran' => 'Sarina Binti Ahmad',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'sarinaahmad508@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:10',
            'password' => '$2y$12$gTwqUsQqosqtysjbDKpg6O1e78pi7wyl9gZ8G5O3CzddBLSKsG1MC',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          34 => 
          array (
            'id' => 35,
            'name' => 'Fatin Zubaidah binti Ghazali',
            'nama_samaran' => 'Fatin Zubaidah binti Ghazali',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'fatin96ghazali@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:10',
            'password' => '$2y$12$VqX8CreVpGwbFXJDgn0Qre9Dm2cGiraTOod4oojhu/GIg2/0o4EVm',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          35 => 
          array (
            'id' => 36,
            'name' => 'Nafizah binti Dollah',
            'nama_samaran' => 'Nafizah binti Dollah',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'nafizahdollah61@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:10',
            'password' => '$2y$12$1q6oiVo.RO9zaWEymiblbe2bX0Lkcnq7nzdFxeHra108DX2ZlwhQi',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:10',
            'updated_at' => '2026-04-03 18:09:10',
          ),
          36 => 
          array (
            'id' => 37,
            'name' => 'Roslina Lahman',
            'nama_samaran' => 'Roslina Lahman',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'linalahman78@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:11',
            'password' => '$2y$12$pHGWnE/nJYd3n.T8AOdZ6uSjTMDQ1q1dnu3UZ3BcEgsg3KFtwz4FW',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:11',
            'updated_at' => '2026-04-03 18:09:11',
          ),
          37 => 
          array (
            'id' => 38,
            'name' => 'Nur Famiza Fazilah',
            'nama_samaran' => 'Nur Famiza Fazilah',
            'tarikh_lahir' => NULL,
            'tarikh_exp_skim_pas' => NULL,
            'email' => 'nazamiza8389@gmail.com',
            'locale' => 'ms',
            'admin_assignment_scope' => NULL,
            'avatar_path' => NULL,
            'email_verified_at' => '2026-04-03 18:09:11',
            'password' => '$2y$12$yDVTyQK62SRaLowYa1u0Pu/2/Q5xoLxH3kaDIqRFpEn0mfX8XIaFu',
            'force_password_change' => 1,
            'remember_token' => NULL,
            'created_at' => '2026-04-03 18:09:11',
            'updated_at' => '2026-04-03 18:09:11',
          ),
        )
        );

        DB::table('roles')->insert(
        array (
          0 => 
          array (
            'id' => 1,
            'name' => 'master_admin',
            'guard_name' => 'web',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          1 => 
          array (
            'id' => 2,
            'name' => 'admin',
            'guard_name' => 'web',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
          2 => 
          array (
            'id' => 3,
            'name' => 'guru',
            'guard_name' => 'web',
            'created_at' => '2026-04-03 16:46:39',
            'updated_at' => '2026-04-03 16:46:39',
          ),
        )
        );

        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    }
}
